# Generated by Django 4.2.5 on 2023-09-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='image_source',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='image_source',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cooler',
            name='image_source',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='cpu',
            name='image_source',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='gpu',
            name='image_source',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='power',
            name='image_source',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='ram',
            name='image_source',
            field=models.URLField(null=True),
        ),
        migrations.AlterField(
            model_name='ssd',
            name='image_source',
            field=models.URLField(null=True),
        ),
    ]
