# Generated by Django 4.2.5 on 2023-09-11 07:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('image_source', models.FileField(null=True, upload_to='media/')),
                ('extinct', models.BooleanField(default=False)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('socket_info', models.CharField(max_length=20, null=True)),
                ('grade', models.CharField(max_length=20, null=True)),
                ('memory_spec', models.CharField(max_length=10, null=True)),
                ('size', models.CharField(max_length=30, null=True)),
                ('pcie3', models.BooleanField(default=False, null=True)),
                ('pcie4', models.BooleanField(default=False, null=True)),
                ('pcie5', models.BooleanField(default=False, null=True)),
                ('m2_count', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'part_mainboard',
            },
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('image_source', models.FileField(null=True, upload_to='media/')),
                ('extinct', models.BooleanField(default=False)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('extended_atx', models.BooleanField(default=False, null=True)),
                ('standard_atx', models.BooleanField(default=False, null=True)),
                ('micro_atx', models.BooleanField(default=False, null=True)),
                ('mini_itx', models.BooleanField(default=False, null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('max_power_depth', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('max_gpu_depth', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('max_cooler_width', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'part_case',
            },
        ),
        migrations.CreateModel(
            name='Cooler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('image_source', models.FileField(null=True, upload_to='media/')),
                ('extinct', models.BooleanField(default=False)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('form', models.CharField(max_length=20, null=True)),
                ('free_warranty_period', models.IntegerField(null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('fan_count', models.IntegerField(null=True)),
                ('max_fan_noise', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'part_cooler',
            },
        ),
        migrations.CreateModel(
            name='Cpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('image_source', models.FileField(null=True, upload_to='media/')),
                ('extinct', models.BooleanField(default=False)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('socket_info', models.CharField(max_length=20, null=True)),
                ('ddr4', models.BooleanField(default=False, null=True)),
                ('ddr5', models.BooleanField(default=False, null=True)),
                ('integrated_graphics', models.BooleanField(default=False, null=True)),
                ('cooler_included', models.BooleanField(default=False, null=True)),
                ('single_score', models.IntegerField(null=True)),
                ('multi_score', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'part_cpu',
            },
        ),
        migrations.CreateModel(
            name='Gpu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('image_source', models.FileField(null=True, upload_to='media/')),
                ('extinct', models.BooleanField(default=False)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('needed_power', models.IntegerField(null=True)),
                ('width', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('thickness', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
            ],
            options={
                'db_table': 'part_gpu',
            },
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('image_source', models.FileField(null=True, upload_to='media/')),
                ('extinct', models.BooleanField(default=False)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('size', models.CharField(max_length=10, null=True)),
                ('grade', models.CharField(max_length=20, null=True)),
                ('output', models.IntegerField(null=True)),
                ('depth', models.DecimalField(decimal_places=2, max_digits=7, null=True)),
                ('free_warranty_period', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'part_power',
            },
        ),
        migrations.CreateModel(
            name='PriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20, null=True)),
                ('part_id', models.PositiveIntegerField()),
                ('start_date', models.DateTimeField(auto_now=True)),
                ('end_date', models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59))),
                ('price', models.IntegerField()),
            ],
            options={
                'db_table': 'price_history',
            },
        ),
        migrations.CreateModel(
            name='Ram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('image_source', models.FileField(null=True, upload_to='media/')),
                ('extinct', models.BooleanField(default=False)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('memory_spec', models.CharField(max_length=10, null=True)),
                ('memory_clerk', models.IntegerField(null=True)),
                ('heat_sink', models.BooleanField(default=False, null=True)),
            ],
            options={
                'db_table': 'part_ram',
            },
        ),
        migrations.CreateModel(
            name='Ssd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('price', models.IntegerField(null=True)),
                ('image_source', models.FileField(null=True, upload_to='media/')),
                ('extinct', models.BooleanField(default=False)),
                ('changed_date', models.DateTimeField(auto_now=True)),
                ('pcie_ver', models.IntegerField(null=True)),
                ('reading_speed', models.IntegerField(null=True)),
                ('writing_speed', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'part_ssd',
            },
        ),
    ]
