# Generated by Django 4.2.5 on 2023-09-18 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0004_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
    ]
