# Generated by Django 4.2.5 on 2023-09-19 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0005_delete_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='gpu',
            name='score',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ram',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ssd',
            name='capacity',
            field=models.IntegerField(null=True),
        ),
    ]
