# Generated by Django 4.2.5 on 2023-09-20 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0007_cat'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cat',
        ),
        migrations.AddField(
            model_name='ssd',
            name='manufacturer',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
