# Generated by Django 4.2.5 on 2023-09-20 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0008_delete_cat_ssd_manufacturer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ssd',
            name='capacity',
            field=models.FloatField(null=True),
        ),
    ]
