# Generated by Django 4.2.5 on 2023-09-21 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0010_case_standard_itx'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='standard_itx',
        ),
    ]
