# Generated by Django 4.2.5 on 2023-09-22 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0011_remove_case_standard_itx'),
    ]

    operations = [
        migrations.RenameField(
            model_name='case',
            old_name='max_cooler_width',
            new_name='max_cooler_depth',
        ),
        migrations.RenameField(
            model_name='ram',
            old_name='memory_clerk',
            new_name='memory_clock',
        ),
    ]
