# Generated by Django 4.2.5 on 2023-09-13 04:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawlers', '0002_alter_board_image_source_alter_case_image_source_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricehistory',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(9999, 12, 31, 23, 59, 59, tzinfo=datetime.timezone.utc)),
        ),
    ]
