# Generated by Django 4.2.5 on 2023-10-05 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('lprice', models.IntegerField(null=True)),
                ('hprice', models.IntegerField(null=True)),
                ('image_source', models.URLField(null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('extinct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'peripheral_keyboard',
            },
        ),
        migrations.CreateModel(
            name='Monitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('lprice', models.IntegerField(null=True)),
                ('hprice', models.IntegerField(null=True)),
                ('image_source', models.URLField(null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('extinct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'peripheral_monitor',
            },
        ),
        migrations.CreateModel(
            name='Mouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('lprice', models.IntegerField(null=True)),
                ('hprice', models.IntegerField(null=True)),
                ('image_source', models.URLField(null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('extinct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'peripheral_mouse',
            },
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('lprice', models.IntegerField(null=True)),
                ('hprice', models.IntegerField(null=True)),
                ('image_source', models.URLField(null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('brand', models.CharField(max_length=50, null=True)),
                ('extinct', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'peripheral_printer',
            },
        ),
    ]
