# Generated by Django 4.2.5 on 2023-10-04 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeripheralReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('peripheral_id', models.IntegerField()),
                ('user_id', models.IntegerField()),
                ('type', models.CharField(max_length=50)),
                ('review', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'peripheral_review',
            },
        ),
        migrations.DeleteModel(
            name='PeripheralSaved',
        ),
    ]
